apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: secrets-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app-demo
          image: krharsh17/test-tester:latest
          ports:
           - containerPort: 5000
          env:
          - name: COLOR_ENV
            valueFrom:
              secretKeyRef:
                name: color
                key: COLOR_ENV

